// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7X705nAvLtGphqVmZjTtZShbSnzFl42g',
    appId: '1:832097497851:web:2f53d21244e765183e765e',
    messagingSenderId: '832097497851',
    projectId: 'mobile-trash-app',
    authDomain: 'mobile-trash-app.firebaseapp.com',
    storageBucket: 'mobile-trash-app.firebasestorage.app',
    measurementId: 'G-23R95QJRHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIvAC8ACeJCIBasXSwaLMcNISE5iYhe5I',
    appId: '1:832097497851:android:c68044792c8d18e43e765e',
    messagingSenderId: '832097497851',
    projectId: 'mobile-trash-app',
    storageBucket: 'mobile-trash-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgQ0NYaqQpQNUuHVH78zTBLzFtV-rCQc',
    appId: '1:832097497851:ios:5f820dcc54e097d23e765e',
    messagingSenderId: '832097497851',
    projectId: 'mobile-trash-app',
    storageBucket: 'mobile-trash-app.appspot.com', // ✅ fixed
    iosBundleId: 'com.example.mobileTrashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7X705nAvLtGphqVmZjTtZShbSnzFl42g',
    appId: '1:832097497851:web:01c273e6161a9bb63e765e',
    messagingSenderId: '832097497851',
    projectId: 'mobile-trash-app',
    authDomain: 'mobile-trash-app.firebaseapp.com',
    storageBucket: 'mobile-trash-app.appspot.com', // ✅ fixed
    measurementId: 'G-6YXY1C2VXK',
  );
}